name: Publish Docker image

on:
  push:
    branches: 
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub private registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: bartvanwoesik/gitops-app
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bartvanwoesik/gitops-app:app-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

  modifygit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
        name: Changing the deployment of git repo
        with:
          repository: 'bartvanwoesik/gitops-manifest'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: Modify the image
        run: |
          git config user.email bartwoesik1@gmail.com
          git config user.name bartvanwoesik
          pwd
          cat manifests/deployment.yaml
          pwd
          sed -i "s+bartvanwoesik/gitops-app.*+bartvanwoesik/gitops-app:app-$RUN_NUMBER+g" manifests/deployment.yaml
          cat manifests/deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
